name: Deploy to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  STAGE: staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0

      - uses: actions/setup-node@v6
        with:
          cache: yarn

      - uses: aws-actions/configure-aws-credentials@v6.2.1
        with:
          role-to-assume: arn:aws:iam::451934005581:role/GithubActions-Serverless-Lambda-Role
          aws-region: ${{ env.AWS_REGION }}

      - run: yarn global add serverless@3.0

      - run: yarn install --frozen-lockfile --production

      - run: make deploy-${{ env.STAGE }}
