name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  STAGE: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v5
        with:
          cache: yarn

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::382373577178:role/GithubActions-Serverless-Lambda-Role
          aws-region: ${{ env.AWS_REGION }}

      - run: yarn global add serverless@3.0

      - run: yarn install --frozen-lockfile --production

      - run: make deploy-${{ env.STAGE }}
